spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comments?serverTimezone=Asia/Seoul
    username: root
    password: ${LOCAL_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update